# Generated by Django 5.1.4 on 2025-01-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_litmarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LimarketParser',
            new_name='LitmarketParser',
        ),
    ]
